---
- name: Build Base Image
  become: true
  gather_facts: true
  hosts: default

  roles:
    - role: shared_handlers
    - role: base_packages
    - role: logging
    - role: docker
    - role: datadog
