---
- name: Do not consider loopback addresses as martian source or destination while routing
  sysctl: name="net.ipv4.conf.all.route_localnet" value=1 sysctl_set=yes state=present reload=yes

- name: Enable IAM roles for tasks - 1
  iptables:
    action: append
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 169.254.170.2
    destination_port: 80
    jump: DNAT
    to_destination: 127.0.0.1:51679

- name: Enable IAM roles for tasks - 2
  iptables:
    action: append
    table: nat
    chain: OUTPUT
    destination: 169.254.170.2
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 51679
