---
- name: apt-get update
  apt: update_cache=yes

- name: Install unattended upgrade packages
  apt: pkg={{ item }} state=latest force=yes
  with_items:
    - apt-listchanges
    - unattended-upgrades

- name: Copy cron update file
  copy:
    src: apt.conf.d/02periodic
    dest: /etc/apt/apt.conf.d/02periodic
    mode: 0644

- name: Copy unattended-upgrade config file
  template:
    src: apt.conf.d/50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: 0644
